
steps:
  - label: ":hammer: Example Script"
    command: "pwsh script.ps1"
    plugins:
      - docker#v3.8.0:
          image: "mcr.microsoft.com/powershell:7.4-ubuntu-22.04"
    artifact_paths: "artifacts/*"